---

- name: Audit_Only | Create local Directories for hosts
  ansible.builtin.file:
      path: "{{ audit_capture_files_dir }}/{{ inventory_hostname }}"
      mode: '0755'
      recurse: true
      state: directory
  when: fetch_audit_files
  delegate_to: localhost
  become: false

- name: Audit_only | Get audits from systems and put in group dir
  ansible.builtin.fetch:
      dest: "{{ audit_capture_files_dir }}/{{ inventory_hostname }}/"
      src: "{{ pre_audit_outfile }}"
      flat: true
      mode: '0644'
  when: fetch_audit_files

- name: Audit_only | Show Audit Summary
  when:
      - audit_only
  ansible.builtin.debug:
      msg: "{{ audit_results.split('\n') }}"

- name: Audit_only | Stop Playbook Audit Only selected
  when:
      - audit_only
  ansible.builtin.meta: end_play
