---

- name: Audit_only | Create local Directories for hosts
  when: fetch_audit_files
  delegate_to: localhost
  become: false
  ansible.builtin.file:
    path: "{{ audit_capture_files_dir }}/{{ inventory_hostname }}"
    mode: '0755'
    recurse: true
    state: directory

- name: Audit_only | Get audits from systems and put in group dir
  when: fetch_audit_files
  ansible.builtin.fetch:
    src: "{{ pre_audit_outfile }}"
    dest: "{{ audit_capture_files_dir }}/{{ inventory_hostname }}/"
    flat: true
    mode: '0644'

- name: Audit_only | Show Audit Summary
  when: audit_only
  ansible.builtin.debug:
    msg: "{{ audit_results.split('\n') }}"

- name: Audit_only | Stop Playbook Audit Only selected
  when: audit_only
  ansible.builtin.meta: end_play
