---

- name: "6.2.2 | PATCH | Ensure access to all logfiles has been configured"
  when:
    - rhel8cis_rule_6_2_2
  tags:
    - level1-server
    - level1-workstation
    - patch
    - logfiles
    - rule_6.2.2
  block:
    - name: "6.2.2 | AUDIT | Ensure access to all logfiles has been configured | find files"
      ansible.builtin.shell: find /var/log/ -type f -perm /g+wx,o+rwx -exec ls {} \;
      changed_when: false
      failed_when: false
      register: discovered_logfiles

    - name: "6.2.2 | AUDIT | Ensure access to all logfiles has been configured | set_fact"
      ansible.builtin.set_fact:
        discovered_logfiles_flattened: "{{ discovered_logfiles | json_query('stdout_lines[*]') | flatten }}"  # noqa: jinja[invalid]
      when:
        - discovered_logfiles.stdout_lines | length > 0
        - discovered_logfiles is defined

    - name: "6.2.2 | PATCH | Ensure access to all logfiles has been configured | change permissions"
      ansible.builtin.file:
        path: "{{ item }}"
        mode: g-rx,o-rwx
      loop: "{{ discovered_logfiles_flattened }}"
      when:
        - discovered_logfiles_flattened is defined
        - item != "/var/log/btmp"
        - item != "/var/log/utmp"
        - item != "/var/log/wtmp"
