---

- name: "SECTION | 6.1.1.1.x | Configure systemd-journald service"
  ansible.builtin.import_tasks:
    file: cis_6.1.1.1.x.yml

- name: "SECTION | 6.1.1.2.x | Configure systemd-journal-remote"
  when: ubtu22cis_syslog_service == 'journald'
  ansible.builtin.import_tasks:
    file: cis_6.1.1.2.x.yml

- name: "SECTION | 6.1.2.x | Configure rsyslog"
  when: ubtu22cis_syslog_service == 'rsyslog'
  ansible.builtin.import_tasks:
    file: cis_6.1.2.x.yml

- name: "SECTION | 6.1.2.8 | Configure LogRotate"
  ansible.builtin.import_tasks:
    file: cis_6.1.2.8.yml

- name: "SECTION | 6.2.1.x | Configure auditd Service"
  ansible.builtin.import_tasks:
    file: cis_6.2.1.x.yml

- name: "SECTION | 6.2.2.x | Configure data retention"
  ansible.builtin.import_tasks:
    file: cis_6.2.2.x.yml

- name: "SECTION | 6.2.3.x | Configure auditd rules"
  ansible.builtin.import_tasks:
    file: cis_6.2.3.x.yml

- name: "SECTION | 6.2.4.x | Configure auditd file access"
  ansible.builtin.import_tasks:
    file: cis_6.2.4.x.yml

- name: "SECTION | 6.3.x | Configure Filesystem Integrity Checking"
  ansible.builtin.import_tasks:
    file: cis_6.3.x.yml
