---

- name: "2.3.1.1 | PATCH | Ensure a single time synchronization daemon is in use"
  when:
    - ubtu22cis_rule_2_3_1_1
  tags:
    - level1-server
    - level1-workstation
    - patch
    - rule_2.3.1.1
    - chrony
    - ntp
    - systemd-timesyncd
    - NIST800-53R5_AU-3
    - NIST800-53R5_AU-12
  block:
    - name: "2.3.1.1 | PATCH | Ensure a single time synchronization daemon is in use | Pkg installed"
      ansible.builtin.package:
        name: "{{ ubtu22cis_time_sync_tool }}"
        state: present

    - name: "2.3.1.1 | PATCH | Ensure a single time synchronization daemon is in use | other pkgs removed"
      when:
        - item != ubtu22cis_time_sync_tool
      ansible.builtin.package:
        name: "{{ item }}"
        state: absent
      loop:
        - chrony
        - ntp
        - systemd-timesyncd

   # note this is somewhat redundant with tasking from 2.3.2 and 2.3.3 but since they can all be run individually
   # to suite ones needs, its fine to have this stop disable and mask code both here and there
    - name: "2.3.1.1 | PATCH | Ensure a single time synchronization daemon is in use | mask service"
      when:
        - item != ubtu22cis_time_sync_tool
      ansible.builtin.service:
        name: "{{ item }}"
        enabled: "{{ ( {{ item }} in ansible_facts.packages) | ternary(false, omit) }}"
        state: "{{ ( {{ item }} in ansible_facts.packages) | ternary('stopped', omit) }}"
        masked: true
        daemon_reload: true
      loop:
        - chrony
        - ntp
        - systemd-timesyncd
