---

- name: "1.1.2.7.1 | AUDIT | Ensure separate partition exists for /var/log/audit"
  when:
    - ubtu22cis_rule_1_1_2_7_1
    - "'/var/log/audit' not in mount_names"
  tags:
    - level2-server
    - level2-workstation
    - audit
    - mounts
    - rule_1.1.2.7.1
  vars:
    warn_control_id: '1.1.2.7.1'
    required_mount: '/var/log/audit'
  block:
    - name: "1.1.2.7.1 | AUDIT | Ensure separate partition exists for /var/log/audit | Warn if partition is absent"
      ansible.builtin.debug:
        msg: "Warning!! {{ required_mount }} doesn't exist. This is a manual task"
      register: var_log_audit_mount_absent
      changed_when: var_log_audit_mount_absent.skipped is undefined

    - name: "1.1.2.7.1 | AUDIT | Ensure separate partition exists for /var/log/audit | Present"
      ansible.builtin.import_tasks:
        file: warning_facts.yml

# skips if mount is absent
- name: |
    "1.1.2.7.2 | PATCH | Ensure nodev option set on /var/log/audit partition"
    "1.1.2.7.3 | PATCH | Ensure nosuid option set on /var/log/audit partition"
    "1.1.2.7.4 | PATCH | Ensure noexec option set on /var/log/audit partition"
  when:
    - "'/var/log/audit' in mount_names"
    - item.mount == "/var/log/audit"
    - ubtu22cis_rule_1_1_2_7_2 or
      ubtu22cis_rule_1_1_2_7_3 or
      ubtu22cis_rule_1_1_2_7_4
  tags:
    - level1-server
    - level1-workstation
    - patch
    - mounts
    - rule_1.1.2.7.2
    - rule_1.1.2.7.3
    - rule_1.1.2.7.4
  notify: Change_requires_reboot
  ansible.posix.mount:
    name: /var/log/audit
    src: "{{ item.device }}"
    fstype: "{{ item.fstype }}"
    state: present
    opts: defaults,{% if ubtu22cis_rule_1_1_2_7_2 %}nodev,{% endif %}{% if ubtu22cis_rule_1_1_2_7_3 %}nosuid,{% endif %}{% if ubtu22cis_rule_1_1_2_7_4 %}noexec{% endif %}
  loop: "{{ ansible_facts.mounts }}"
  loop_control:
    label: "{{ item.device }}"
