---

# This is a playbook to test the tasks.
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  vars:
    ansible_user: "{{ lookup('env', 'USER') }}"
    system_is_container: true
    ubtu22cis_rule_5_2_4: false

  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
